---
# MariaDB installation
- name: MariaDB .:. Install python3-pymysql
  apt: 
    update_cache: true
    name: python3-pymysql
    state: present

- name: MariaDB .:. Test if root .mysql file exists
  stat:
    path: "/root/.my.cnf"
  register: mariadb_mycnf_result

- name: MariaDB .:. Test if data has been moved
  stat:
    path: "/opt/data/mysql/ibdata1"
  register: mariadb_data_moved

- name: MariaDB .:. Install MariaDB
  apt: 
    update_cache: false
    name: mariadb-server
    state: present
  when: mariadb_mycnf_result.stat.exists == false

- name: MariaDB .:. Configure bind address
  replace:
      path: /etc/mysql/mariadb.conf.d/50-server.cnf
      regexp: "^bind-address.*"
      replace: "bind-address={{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
  when: mariadb_mycnf_result.stat.exists == false

- name: MariaDB .:. Copy mysql data directory to storage device
  raw: 'cp -R -p /var/lib/mysql /opt/data/mysql && rm -fR /var/lib/mysql'
  when: 
    - mariadb_mycnf_result.stat.exists == false
    - mariadb_data_moved.stat.exists == false

- name: MariaDB .:. Change mysql data directory
  replace:
      path: /etc/mysql/mariadb.conf.d/50-server.cnf
      regexp: "^datadir.*"
      replace: "datadir = /opt/data/mysql"
  when: 
    - mariadb_mycnf_result.stat.exists == false
    - mariadb_data_moved.stat.exists == false

- name: MariaDB .:. Restart if needed
  service:
    name: mariadb
    state: restarted
    enabled: yes
  when: 
    - mariadb_mycnf_result.stat.exists == false
