---
# MariaDB installation
- name: MariaDB .:. Install required dependencies
  apt:
    update_cache: true
    name: ['software-properties-common', 'python3-pymysql']
    state: present

- name: MariaDB .:. Add MariaDB repository keys
  apt_key:
    keyserver: "{{ mariadb_repo_keyserver }}"
    id: "{{ mariadb_repo_key }}"
    state: "present"

- name: MariaDB .:. Pin MariaDB repository
  template:
    src: "mariadb_repo.j2"
    dest: "/etc/apt/preferences.d/mariadb"

- name: MariaDB .:. Add MariaDB repository
  apt_repository:
    repo: "{{ mariadb_repo }}"
    state: "present"

- name: MariaDB .:. Test if root .mysql file exists
  stat:
    path: "/root/.my.cnf"
  register: mariadb_mycnf_result

- name: MariaDB .:. Test if data has been moved
  stat:
    path: "/opt/data/mysql/ibdata1"
  register: mariadb_data_moved

- name: MariaDB .:. Install MariaDB
  apt:
    update_cache: false
    name: "{{ item }}"
    state: present
  when: mariadb_mycnf_result.stat.exists == false
  with_items:
    - "mariadb-server-{{ mariadb_version }}"
    - socat
    - mariadb-backup

- name: MariaDB .:. Configure bind address
  replace:
    path: /etc/mysql/my.cnf
    regexp: "^bind-address.*"
    replace: "bind-address={{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
  when: mariadb_mycnf_result.stat.exists == false

- name: MariaDB .:. Stop the service
  service:
    name: mysql
    state: stopped
    enabled: yes
  when:
    - mariadb_mycnf_result.stat.exists == false

- name: MariaDB .:. Copy mysql data directory to storage device
  raw: 'cp -R -p /var/lib/mysql /opt/data/mysql && rm -fR /var/lib/mysql'
  when:
    - mariadb_mycnf_result.stat.exists == false
    - mariadb_data_moved.stat.exists == false

- name: MariaDB .:. Change mysql data directory
  replace:
      path: /etc/mysql/my.cnf
      regexp: "^datadir.*"
      replace: "datadir = /opt/data/mysql"
  when:
    - mariadb_mycnf_result.stat.exists == false
    - mariadb_data_moved.stat.exists == false

- name: MariaDB .:. Restart if needed
  service:
    name: mysql
    state: restarted
    enabled: yes
  when:
    - mariadb_mycnf_result.stat.exists == false
