---
# MariaDB installation
- name: Install python3-pymysql
  apt: 
    update_cache: true
    name: python3-pymysql
    state: present

- name: Clean mariadb root password if present
  file:
    state: absent
    path: "/root/.my.cnf"

- name: Install mariadb
  apt: 
    update_cache: false
    name: mariadb-server
    state: present

# Ubuntu configure MariaDB to start using socket
- name: Set root password
  mysql_user:
    login_user: 'root'
    name: root
    password: '{{mariadb_root_password}}'
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Configure bind address
  replace:
      path: /etc/mysql/mariadb.conf.d/50-server.cnf
      regexp: "^bind-address.*"
      replace: "bind-address={{hostvars[inventory_hostname]['ansible_default_ipv4']['address']}}"

- name: Restart always mariadb 
  service:
    name: mariadb
    state: restarted
    enabled: yes

- name: Create root configuration file
  template:
    src: 'root-my.cnf.j2'
    dest: '/root/.my.cnf'
    owner: 'root'
    group: 'root'
    mode: '0600'
