language: python
python:
  - "2.7"
  - "3.7"

addons:
  mariadb: '10.4'

before_install:
  - sudo mysql -e 'CREATE DATABASE IF NOT EXISTS test;'

install:
  - curl -sLo terraform.zip https://releases.hashicorp.com/terraform/0.12.20/terraform_0.12.20_linux_amd64.zip
  - unzip terraform.zip
  - sudo mv terraform /usr/local/bin
  - rm terraform.zip
  - curl -sLo kubeval.tar.gz https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz
  - tar xf kubeval.tar.gz
  - sudo mv kubeval /usr/local/bin
  - pip install ansible
  - pip install -r requirements.txt
  - ansible-galaxy install -r playbooks/requirements.yml
  - git clone --branch v2.12.0 https://github.com/kubernetes-sigs/kubespray.git playbooks/kubespray

script:
  - ssh-keygen -t rsa -b 4096 -N '' -f ssh_wai_key
  - cd infrastructure
  - terraform init -backend=false -no-color
  - terraform validate -no-color
  - cd ..
  - ansible-playbook playbooks/wai.yml -i playbooks/inventory/30-localhost --syntax-check
  - ansible-playbook playbooks/wai.yml -i playbooks/inventory/30-localhost -t templates
  - kubeval playbooks/compiled-templates/k8s/*.yml
  - kubeval playbooks/compiled-templates/k8s/**/*.yml
  - cat playbooks/compiled-templates/db/*.sql | sudo mysql test -v
  - cat playbooks/compiled-templates/db/**/*.sql | sudo mysql test -v
