---
# Galera role
- name: Galera .:. Fail if galera members are less than 3
  fail:
    msg: "Wrong configuration for Galera cluster: less than 3 members found"
  when: "groups[group_names[0]] | length < 3"

- name: Galera .:. Test if galera has been configured
  stat:
    path: "/etc/mysql/conf.d/galera.cnf"
  register: galera_present_result

- include_role:
    name: mariadb
  when: galera_present_result.stat.exists == false

- name: Galera .:. Create configuration file
  template:
    src: "galera.yml.j2"
    dest: "/etc/mysql/conf.d/galera.cnf"
    owner: "root"
    group: "root"
    mode: "0644"
  when: galera_present_result.stat.exists == false

- name: Galera .:. Identify first node
  set_fact:
    galera_first_node: true
  with_items: ["galera-prod", "galera-play"]
  when: 
    - groups[item]|length > 0
    - inventory_hostname == groups[item][0]

- name: Galera .:. Stop MariaDB
  service:
    name: mariadb
    state: stopped
    enabled: yes
  when: galera_present_result.stat.exists == false

- name: Galera .:. Create cluster
  raw: "galera_new_cluster"
  when:
    - "galera_first_node is defined"
    - "galera_present_result.stat.exists == false"

- name: Galera .:. Restart MariaDB on other nodes
  service:
    name: mariadb
    state: restarted
    enabled: yes
  when:
    - "galera_first_node is not defined"
    - "galera_present_result.stat.exists == false"
