# WAI
wai_k8s_deployment_dir: /opt/data/scripts/wai
wai_k8s_namespaces:
  - wai-prod
  - wai-play
  - wai-stag
wai_matomo_base_image: giafar/wai-matomo:3.7.0-fpm
wai_kube_state_metrics_version: v1.5.0
wai_kube_state_metrics: 'https://codeload.github.com/kubernetes/kube-state-metrics/zip/{{ wai_kube_state_metrics_version }}'
wai_kubectl: /usr/local/bin/kubectl
wai_base_http_port: 30080
wai_base_https_port: 30443
# Elastic version used for Elasticsearch, Kibana and Beats.
# These vars override default settings of role elastic.elasticsearch and are used in wai roles kibana and metricbeat
es_version: 6.6.0
es_apt_key: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
es_apt_url: "deb https://artifacts.elastic.co/packages/6.x/apt stable main"
# Metricbeat output
metricbeat_output_elastic: '{{ groups["elastic"] | map("extract", hostvars, ["ansible_default_ipv4", "address"]) | list | to_json }}'

# Override path used to store Docker data in kubespray all\docker.yml
docker_daemon_graph: "/opt/data/docker"

