- name: Adding Elastic PGP key
  apt_key:
    url: "{{ es_apt_key }}"
    state: present

- name: Updating repository
  apt_repository:
    repo: "{{ es_apt_url }}"
    state: present

- name: Installing Kibana
  apt:
    update_cache: yes
    name: kibana={{ es_version }}

- name: Configure Kibana
  template:
    src: kibana.yml.j2
    dest: /etc/kibana/kibana.yml
  notify:
    - restart kibana

- name: Ensure Kibana is up and running
  service:
    name: kibana
    state: started
    enabled: yes
