---
kind: ConfigMap
apiVersion: v1
metadata:
  name: kong-configmap
  namespace: {{ item }}
data:
    KONG_DATABASE: postgres
    KONG_PG_DATABASE: kong
    KONG_PG_USER: {{ kong[item].pgsql.user }}
    KONG_PG_HOST: kong-pgsql-headless
    KONG_LOG_LEVEL: info
    KONG_PROXY_ACCESS_LOG: /dev/stdout
    KONG_ADMIN_ACCESS_LOG: /dev/stdout
    KONG_PROXY_ERROR_LOG: /dev/stderr
    KONG_ADMIN_ERROR_LOG: /dev/stderr
    KONG_ADMIN_LISTEN: 0.0.0.0:8001,0.0.0.0:8444 ssl
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: kong-secret
  namespace: {{ item }}
data:
    KONG_PG_PASSWORD: {{ kong[item].pgsql.password | b64encode }}
---
apiVersion: v1
kind: Service
metadata:
  name: kong-service
  namespace: {{ item }}
spec:
  ports:
  - name: http
    protocol: TCP
    port: 8000
  - name: https
    protocol: TCP
    port: 8443
  selector:
    app: kong
---
apiVersion: v1
kind: Service
metadata:
  name: kong-admin-service
  namespace: {{ item }}
spec:
  ports:
  - name: admin-http
    protocol: TCP
    port: 8001
  - name: admin-https
    protocol: TCP
    port: 8444
  selector:
    app: kong
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong
  namespace: {{ item }}
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: kong
  template:
    metadata:
      annotations:
        releaseDate: now
      labels:
        app: kong
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - kong
            topologyKey: "kubernetes.io/hostname"
      containers:
      - image: {{ wai_kong_image }}:{{ 'latest' if item == 'wai-stag' else wai_kong_image_tag }}
        name: kong
        envFrom:
          - configMapRef:
              name: kong-configmap
          - secretRef:
              name: kong-secret
        resources:
          limits:
            cpu: "0.25"
            memory: "512Mi"
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 8001
          name: admin-http
        - containerPort: 8443
          name: https
        - containerPort: 8444
          name: admin-https
