# Use bastion host
ansible_ssh_common_args: "{% if 'wai-bastion' in groups %} -o ProxyCommand='ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -W %h:%p {{ hostvars[groups['wai-bastion'][0]]['ansible_user'] }}@{{ hostvars[groups['wai-bastion'][0]]['ansible_host'] }}{% if ansible_ssh_private_key_file is defined %} -i {{ ansible_ssh_private_key_file }}{% endif %}'{% endif %}"
ansible_ssh_private_key_file: ./ssh_wai_key

# Development tasks
wai_development: false

# Ensure python v3 is used on the remote hosts
ansible_python_interpreter: /usr/bin/python3

# WAI alert destination
wai_alert_email_destination:
  - example@example.org
  - test@test.it

# WAI
wai_k8s_deployment_dir: /opt/data/scripts/wai
wai_k8s_namespaces:
  - wai-prod
  - wai-play
  - wai-stag

# Database
db_dump_dir: /root

# Base fqdn domain
wai_base_domain:
  wai-prod: webanalytics.italia.it
  wai-play: play.webanalytics.italia.it
  wai-stag: staging.webanalytics.italia.it

# WAI Load Balancer
# The following IP addresses are just placeholders and must be replaced with the real ones after all the LBs are created.
wai_load_balancer:
  wai-prod:
    elastic:
      - 10.0.30.17
    rdbms:
      - 10.0.20.16
      - 10.0.20.11
  wai-play:
    elastic:
      - 10.0.30.17
    rdbms:
      - 10.0.200.7
  wai-stag:
    elastic:
      - 10.0.30.17
    rdbms:
      - 10.0.100.101

# WAI infrastructure CIDR
wai_infrastructure_cidr: 10.0.0.0/16

# Hostnames
wai_hostname: { ingestion: ingestion, portal: www, api: api }

# Mapping between public ip address and internal load balancer
# The following IP addresses are just placeholders and must be replaced with the real ones after all the private ip ports are created.
wai_ip_addresses:
  wai-prod:
    public_ip: 131.1.241.153
    private_ip: 10.0.10.250
  wai-play:
    public_ip: 131.1.241.135
    private_ip: 10.0.10.251
  wai-stag:
    public_ip: 131.1.241.131
    private_ip: 10.0.10.252

# Helm
helm:
  cert_manager:
    version: v1.0.3

# Matomo POD size configuration
wai_matomo_pod_size:
  wai-prod: { wai-portal: 4, wai-reporting: 4, wai-api: 4, matomo-portal: 4, matomo-worker: 8, matomo-ingestion: 8, matomo-api: 4 }
  wai-play: { wai-portal: 4, wai-reporting: 4, wai-api: 4, matomo-portal: 4, matomo-worker: 8, matomo-ingestion: 8, matomo-api: 4 }
  wai-stag: { wai-portal: 2, wai-reporting: 2, wai-api: 2, matomo-portal: 2, matomo-worker: 2, matomo-ingestion: 2, matomo-api: 2 }

# Resource Quota
wai_k8s_resource_quota:
  wai-prod: { requests.cpu: "50", requests.memory: "54Gi", limits.cpu: "60", limits.memory: "64Gi" }
  wai-play: { requests.cpu: "50", requests.memory: "54Gi", limits.cpu: "50", limits.memory: "64Gi" }
  wai-stag: { requests.cpu: "24", requests.memory: "30Gi", limits.cpu: "34", limits.memory: "40Gi" }

# IPA Redisearch image
wai_ipa_redisearch_image: webanalyticsitalia/wai-ipa-redisearch
wai_ipa_redisearch_image_tag: 5.0.9-stable

# Portal image
wai_portal_image: webanalyticsitalia/wai-portal
wai_portal_image_tag: 1.4.1-beta
wai_portal_matomo_sub_path: /matomo
wai_portal_environments:
  wai-prod: production
  wai-play: public-playground
  wai-stag: staging

# RediSearch Image
wai_redisearch_image: webanalyticsitalia/wai-redisearch
wai_redisearch_image_tag: 5.0.9-stable
wai_redisearch_slave_count: 2

# Redis
redis_image_version: 5.0.7

# Matomo Image
wai_matomo_image: webanalyticsitalia/wai-matomo
wai_matomo_image_tag: 3.13.5-1

# Kubectl executable
wai_kubectl: /usr/local/bin/kubectl

# Base K8S Node port for http
wai_base_http_port: 30080

# Base K8S Node port for https
wai_base_https_port: 30443

# Elastic version used for Elasticsearch, Kibana and Beats.
# These vars override default settings of role elastic.elasticsearch and are used in wai roles kibana
es_version: 7.9.1
es_major_version: 7.x
es_apt_key: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
es_apt_url: "deb https://artifacts.elastic.co/packages/{{ es_major_version }}/apt stable main"

kibana_elastic_hosts: "https://{{ hostvars[groups['elastic'][0]].ansible_default_ipv4.address }}:9200"

# Override path used to store Docker data in kubespray all\docker.yml
docker_daemon_graph: "/opt/data/docker"

# GlusterFS
gluster_apt_repo: ppa:gluster/glusterfs-5
gluster_package_version: 5.*

# MariaDB repo info
mariadb_version: "10.5"
mariadb_repo: "deb [arch=amd64,i386,ppc64el] http://mariadb.mirrors.ovh.net/MariaDB/repo/{{ mariadb_version }}/{{ ansible_distribution|lower }} {{ ansible_distribution_release|lower }} main"
mariadb_repo_key: "0xF1656F24C74CD1D8"
mariadb_repo_keyserver: "keyserver.ubuntu.com"
mariadb_repo_origin: mariadb.mirrors.ovh.net

# Prometheus Node Exporter override vars
prometheus_exporter_url: https://github.com/prometheus/node_exporter/releases/download/v0.18.1/node_exporter-0.18.1.linux-amd64.tar.gz
# Prometheus MySQL exporter override vars
prometheus_mysqld_exporter_url: https://github.com/prometheus/mysqld_exporter/releases/download/v0.12.1/mysqld_exporter-0.12.1.linux-amd64.tar.gz

# Heketi role overrides
heketi_url: https://github.com/heketi/heketi/releases/download/v9.0.0/heketi-v9.0.0.linux.amd64.tar.gz
heketi_enable_tls: true
heketi_port: 8443

# OpenVPN
# This is needed to set IP filtered login to Matomo
openvpn_server_addr: 1.2.3.4
