---
# Configure Matomo database
- hosts:
    - galera-prod[0]
    - galera-prod-slave[0]
    - galera-play[0]
    - mariadb-stag[0]
  tasks:
    - include_vars:
        file: password.yml

    - name: Database .:. Install required software
      apt:
        name: ["python3-pymysql"]
        state: present

    - name: Database .:. Test if prod password
      set_fact:
        wai_environment: wai-prod
      when: inventory_hostname in groups['galera-prod']

    - name: Database .:. Test if play password
      set_fact:
        wai_environment: wai-play
      when: inventory_hostname in groups['galera-play']

    - name: Database .:. Test if stag password
      set_fact:
        wai_environment: wai-stag
      when: inventory_hostname in groups['mariadb-stag']

    - name: Database .:. Fail if password is not found
      fail:
        msg: "Password for the current environment not found"
      when: "wai_environment is not defined or wai_database_credentials[wai_environment] is not defined"

    - name: Database .:. Calculate matomo super user password
      set_fact:
        matomo_database_superuser_password: "{{ matomo_vars.super_user.password | md5 | password_hash('bcrypt') }}"
        portal_database_superuser_password: "{{ portal_vars.super_user.password  | password_hash('bcrypt') }}"

    - name: Database .:. Prepare matomo template sql script
      vars:
        item: "{{ wai_environment }}"
      template:
        src: "mariadb/matomo_3_12_0.sql.j2"
        dest: "/root/matomo_3_12_0.sql"

    - name: Database .:. Prepare wai template sql script
      template:
        src: "mariadb/portal_1_0_0.sql.j2"
        dest: "/root/portal_1_0_0.sql"

    - name: Database .:. Test if matomo database is present
      shell: mysql -e 'SHOW TABLES;' matomo | grep log_action
      register: matomo_db_status
      failed_when: matomo_db_status.rc == 2

    - name: Database .:. Test if portal database is present
      shell: mysql -e 'SHOW TABLES;' wai | grep websites
      register: wai_db_status
      failed_when: wai_db_status.rc == 2

    - name: Database .:. Import Matomo database
      mysql_db:
        name: matomo
        login_unix_socket: "/var/run/mysqld/mysqld.sock"
        state: import
        target: "/root/matomo_3_13_0.sql"
      when: matomo_db_status.rc != 0

    - name: Database .:. Create WAI database
      mysql_db:
        name: wai
        login_unix_socket: "/var/run/mysqld/mysqld.sock"
        state: import
        target: "/root/portal_1_0_0.sql"
      when: wai_db_status.rc != 0

    - name: Database .:.  Create Matomo super user
      mysql_user:
        name: matomo-admin
        login_unix_socket: "/var/run/mysqld/mysqld.sock"
        password: "{{ wai_database_credentials[wai_environment]['matomo-admin'] }}"
        priv: "matomo.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER,CREATE TEMPORARY TABLES,LOCK TABLES/*.*:FILE"
        host: "%"
        state: present

    - name: Database .:.  Create Matomo readonly user
      mysql_user:
        name: matomo-user
        login_unix_socket: "/var/run/mysqld/mysqld.sock"
        password: "{{ wai_database_credentials[wai_environment]['matomo-user'] }}"
        priv: "matomo.*:SELECT,CREATE TEMPORARY TABLES"
        host: "%"
        state: present

    - name: Database .:.  Create WAI super user
      mysql_user:
        name: wai-admin
        login_unix_socket: "/var/run/mysqld/mysqld.sock"
        password: "{{ wai_database_credentials[wai_environment]['wai-admin'] }}"
        priv: "wai.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER,CREATE TEMPORARY TABLES,LOCK TABLES"
        host: "%"
        state: present

    - name: Database .:. Set root password
      mysql_user:
        login_user: "root"
        name: root
        password: "{{ wai_database_credentials.root }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock

- hosts:
    - galera-prod
    - galera-prod-slave
    - galera-play
    - mariadb-stag
  tasks:
    - include_vars:
        file: password.yml

    - name: Database .:. Create root configuration file
      vars:
        database_root_password: "{{ wai_database_credentials.root }}"
      template:
        src: "mariadb/root-my.cnf.j2"
        dest: "/root/.my.cnf"
        owner: "root"
        group: "root"
        mode: "0600"
