---
# Configure Matomo database
- hosts:
    - galera-prod[0]
    - galera-play[0]
    - mariadb-stag[0]
  tasks:
    - include_vars:
        file: password.yml

    - name: Database .:. Install required software
      apt:
        name: ["python3-pymysql"]
        state: present

    - name: Database .:. Test if prod password
      set_fact:
        wai_environment: wai-prod
      when: inventory_hostname in groups['galera-prod']

    - name: Database .:. Test if play password
      set_fact:
        wai_environment: wai-play
      when: inventory_hostname in groups['galera-play']

    - name: Database .:. Test if stag password
      set_fact:
        wai_environment: wai-stag
      when: inventory_hostname in groups['mariadb-stag']

    - name: Database .:. Fail if password is not found
      fail:
        msg: "Password for the current environment not found"
      when: "wai_environment is not defined or wai_database_password[wai_environment] is not defined"

    - name: Database .:. Calculate matomo super user password
      set_fact:
        matomo_database_superuser_password: "{{ matomo_vars.super_user.password | password_hash('md5', matomo_vars.salt) }}"

    - name: Database .:. Prepare matomo template sql script
      template:
        src: "mariadb/matomo_3_8_1-data.sql.j2"
        dest: "/root/matomo_3_8_1-data.sql"

    - name: Database .:. Test if matomo database is present
      shell: mysql -e 'SHOW DATABASES;' | grep matomo
      register: matomo_db_status
      failed_when: matomo_db_status.rc == 2

    - name: Database .:. Import Matomo database
      mysql_db:
        name: matomo
        login_unix_socket: "/var/run/mysqld/mysqld.sock"
        state: import
        target: "/root/matomo_3_8_1-data.sql"
      when: matomo_db_status.rc != 0

    - name: Database .:. Create WAI database
      mysql_db:
        name: wai
        login_unix_socket: "/var/run/mysqld/mysqld.sock"
        state: present

    - name: Database .:.  Create Matomo super user
      mysql_user:
        name: matomo-admin
        login_unix_socket: "/var/run/mysqld/mysqld.sock"
        password: "{{ wai_database_password[wai_environment]['matomo-admin'] }}"
        priv: "matomo.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER,CREATE TEMPORARY TABLES,LOCK TABLES"
        host: "%"
        state: present

    - name: Database .:.  Create Matomo readonly user
      mysql_user:
        name: matomo-user
        login_unix_socket: "/var/run/mysqld/mysqld.sock"
        password: "{{ wai_database_password[wai_environment]['matomo-user'] }}"
        priv: "matomo.*:SELECT"
        host: "%"
        state: present

    - name: Database .:.  Create WAI super user
      mysql_user:
        name: wai-admin
        login_unix_socket: "/var/run/mysqld/mysqld.sock"
        password: "{{ wai_database_password[wai_environment]['wai-admin'] }}"
        priv: "wai.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER,CREATE TEMPORARY TABLES,LOCK TABLES"
        host: "%"
        state: present

    - name: Database .:. Set root password
      mysql_user:
        login_user: "root"
        name: root
        password: "{{ wai_database_password[wai_environment]['root'] }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Database .:. Set database password
      set_fact:
        database_root_password: "{{ wai_database_password[wai_environment]['root'] }}"

    - name: Database .:. Create root configuration file
      template:
        src: "mariadb/root-my.cnf.j2"
        dest: "/root/.my.cnf"
        owner: "root"
        group: "root"
        mode: "0600"
