---
# Compile K8S resources templates
- name: K8S .:. Create destination directories
  file:
    path: "{{ wai_k8s_deployment_dir }}/{{ item }}"
    state: directory
  with_items: "{{ wai_k8s_namespaces }}"

- name: K8S .:. Prepare cluster object deployment
  template:
    src: "{{ item }}"
    dest : "{{ wai_k8s_deployment_dir }}/{{ item | basename | regex_replace('.j2','') }}"
  with_fileglob:
    - templates/k8s/global/*.j2

- name: K8S .:. Calculate namespace dependant objects
  set_fact:
    namespace_file: "{{ namespace_file | default([]) + [ item ] }}"
  with_fileglob:
    - templates/k8s/namespace/*.j2

- name: K8S .:. Prepare namespace dependant deployment
  vars:
    item: "{{ filevar[0] }}"
  template:
    src: "{{ filevar[1] }}"
    dest : "{{ wai_k8s_deployment_dir }}/{{ filevar[0] }}/{{ filevar[1] | basename | regex_replace('.j2','') }}"
  with_nested:
    - "{{ wai_k8s_namespaces }}"
    - "{{ namespace_file }}"
  loop_control:
    loop_var: filevar

- name: K8S .:. Prepare infrastructure ca certificate config map
  vars:
    certificate_lines:  "{{ lookup('file', wai_infrastructure_ca.root_folder + '/crt/wai-ca.crt').splitlines() }}"
  template:
    src: "k8s/infrastructure-ca-cm.yml.j2"
    dest: "{{ wai_k8s_deployment_dir }}/{{ item }}/00_infrastruxture-ca-config-map.yml"
  with_items: "{{ wai_k8s_namespaces }}"

# Matomo Ingestion
- name: K8S .:. Prepare Matomo Ingestion deployment file
  vars:
    matomo_app_filename: "/matomo.php"
    matomo_name: "matomo-ingestion"
    matomo_pod_size_index: "matomo-ingestion"
    matomo_nginx_jailed: true
    matomo_create_ingress: true
    matomo_ingress_fqdn_index: "ingestion"
  template:
    dest: "{{ wai_k8s_deployment_dir }}/{{ item }}/99_matomo-ingestion.yml"
    src: k8s/jail/matomo-jail.yml.j2
  with_items: "{{ wai_k8s_namespaces }}"

# Matomo API
- name: K8S .:. Prepare Matomo API deployment file
  vars:
    matomo_app_filename: "/index.php"
    matomo_name: "matomo-api"
    matomo_pod_size_index: "matomo-api"
    matomo_nginx_jailed: true
    matomo_create_ingress: false
  template:
    dest: "{{ wai_k8s_deployment_dir }}/{{ item }}/99_matomo-api.yml"
    src: k8s/jail/matomo-jail.yml.j2
  with_items: "{{ wai_k8s_namespaces }}"

# Matomo Portal
- name: K8S .:. Prepare Matomo portal deployment file
  vars:
    matomo_app_filename: "/index.php"
    matomo_name: "matomo"
    matomo_pod_size_index: "matomo-portal"
    matomo_nginx_jailed: false
    matomo_create_ingress: false
  template:
    dest: "{{ wai_k8s_deployment_dir }}/{{ item }}/99_matomo-portal.yml"
    src: k8s/jail/matomo-jail.yml.j2
  with_items: "{{ wai_k8s_namespaces }}"
