---
# Deploy K8S WAI Resources
- hosts: kube-master[0]
  tasks:
    - include_vars:
        file: password.yml

    # Base objects
    - name: K8S .:. Create destination directories
      file:
        path: "{{ wai_k8s_deployment_dir }}/{{ item }}"
        state: directory
      with_items: "{{ wai_k8s_namespaces }}"

    - name: K8S .:. Prepare cluster roles
      template:
        dest: "{{ wai_k8s_deployment_dir }}/k8s-cluster-roles.yml"
        src: k8s/k8s-cluster-roles.yml.j2

    - name: K8S .:. Deploy cluster roles
      kube:
        name: "k8s-cluster-roles"
        kubectl: "{{ wai_kubectl }}"
        state: "latest"
        filename: "{{ wai_k8s_deployment_dir }}/k8s-cluster-roles.yml"

    - name: K8S .:. Prepare base objects template
      template:
        dest: "{{ wai_k8s_deployment_dir }}/{{ item }}/k8s-deployment.yml"
        src: k8s/k8s-deployment.yml.j2
      with_items: "{{ wai_k8s_namespaces }}"

    - name: K8S .:. Deploy base objects template
      kube:
        name: "k8s-deployment"
        kubectl: "{{ wai_kubectl }}"
        state: "latest"
        filename: "{{ wai_k8s_deployment_dir }}/{{ item }}/k8s-deployment.yml"
      with_items: "{{ wai_k8s_namespaces }}"

    # Fluentd
    - name: K8S .:. Prepare Fluentd files
      template:
        dest: "{{ wai_k8s_deployment_dir }}/fluentd.yml"
        src: k8s/k8s-fluentd.yml.j2

    - name: K8S .:. Deploy Fluentd
      kube:
        kubectl: "{{ wai_kubectl }}"
        state: "latest"
        filename: "{{ wai_k8s_deployment_dir }}/fluentd.yml"

    # GlusterFS
    - name: K8S .:. Prepare GlusterFS endpoints
      template:
        dest: "{{ wai_k8s_deployment_dir }}/{{ item }}/glusterfs.yml"
        src: k8s/glusterfs.yml.j2
      with_items: "{{ wai_k8s_namespaces }}"

    - name: K8S .:. Deploy GlusterFS
      kube:
        name: "glusterfs-{{ item }}"
        kubectl: "{{ wai_kubectl }}"
        state: "latest"
        filename: "{{ wai_k8s_deployment_dir }}/{{ item }}/glusterfs.yml"
      with_items: "{{ wai_k8s_namespaces }}"

    # Kube State Metrics
    - name: K8S .:. Download Kube State Metrics
      get_url:
        url: "{{ wai_kube_state_metrics }}"
        dest: "{{ wai_k8s_deployment_dir }}/kube-state-metrics-{{ wai_kube_state_metrics_version }}.zip"

    - name: K8S .:. Extract Kube State Metrics
      unarchive:
        src: "{{ wai_k8s_deployment_dir }}/kube-state-metrics-{{ wai_kube_state_metrics_version }}.zip"
        dest: "{{ wai_k8s_deployment_dir }}"
        remote_src: yes

    - name: K8S .:. Enumerate Kube State Metrics in {{ wai_k8s_deployment_dir }}/{{ wai_kube_state_metrics_output_dir }}/kubernetes
      find:
        paths: "{{ wai_k8s_deployment_dir }}/{{ wai_kube_state_metrics_output_dir }}/kubernetes"
        patterns: "*.yml,*.yaml"
      register: ksm_deployment_files

    - name: K8S .:. Deploy Kube State Metrics
      kube:
        name: "kube-state-metrics"
        kubectl: "{{ wai_kubectl }}"
        state: "latest"
        filename: "{{ item.path }}"
      with_items:
        - "{{ ksm_deployment_files.files }}"

    # Metricbeat
    - name: K8S .:. Configure Elasticsearch hosts for metricbeat
      set_fact:
        elastic_url: "http://{{ item }}:9200"
      with_items: '{{ groups["elastic"] | map("extract", hostvars, ["ansible_default_ipv4", "address"]) | list }}'
      register: kibana_elastic_hosts_list

    - name: K8S .:. Build Elasticsearch host array
      set_fact:
        kibana_elastic_hosts: '{{ kibana_elastic_hosts_list.results | map(attribute="ansible_facts.elastic_url") | list }}'

    - name: K8S .:. Prepare Metricbeat DaemonSet and services
      template:
        dest: "{{ wai_k8s_deployment_dir }}/metricbeat.yml"
        src: k8s/metricbeat.yml.j2

    - name: K8S .:. Deploy Metricbeat DaemonSet and services
      kube:
        name: "metricbeat"
        kubectl: "{{ wai_kubectl }}"
        state: "latest"
        filename: "{{ wai_k8s_deployment_dir }}/metricbeat.yml"

    # Deploy Ingress controller
    - name: K8S .:. Prepare Ingress controller deployment file
      template:
        dest: "{{ wai_k8s_deployment_dir }}/ingress-controller.yml"
        src: k8s/ingress-controller.yml.j2

    - name: K8S .:. Deploy Ingress controller
      kube:
        kubectl: "{{ wai_kubectl }}"
        state: "latest"
        filename: "{{ wai_k8s_deployment_dir }}/ingress-controller.yml"

    # Deploy K8S matomo default configmap
    - name: K8S .:. Prepare Matomo configmap deployment file
      template:
        dest: "{{ wai_k8s_deployment_dir }}/{{ item }}/matomo-config-map.yml"
        src: k8s/matomo-config-map.yml.j2
      with_items: "{{ wai_k8s_namespaces }}"

    - name: K8S .:. Deploy Matomo config map
      kube:
        name: "matomo-php-config-map"
        kubectl: "{{ wai_kubectl }}"
        filename: "{{ wai_k8s_deployment_dir }}/{{ item }}/matomo-config-map.yml"
        state: "latest"
      with_items: "{{ wai_k8s_namespaces }}"

    # Deploy K8S matomo secrets
    - name: K8S .:. Prepare matomo secrets
      template:
        dest: "{{ wai_k8s_deployment_dir }}/{{ item }}/matomo-secrets.yml"
        src: k8s/matomo-secrets.yml.j2
      with_items: "{{ wai_k8s_namespaces }}"

    - name: K8S .:. Deploy Matomo secrets
      kube:
        name: "matomo-secrets"
        kubectl: "{{ wai_kubectl }}"
        filename: "{{ wai_k8s_deployment_dir }}/{{ item }}/matomo-secrets.yml"
        state: "latest"
      with_items: "{{ wai_k8s_namespaces }}"
    
    # Matomo Ingestion
    - name: K8S .:. Prepare Matomo Ingestion template vars
      set_fact:
        matomo_app_filename: "/piwik.php"
        matomo_name: "matomo-ingestion"
        matomo_pod_size_index: "matomo-ingestion"
        matomo_nginx_jailed: true
        matomo_create_ingress: true
        matomo_enable_session: false
        matomo_ingress_fqdn_index: "ingestion"
        matomo_database_user: "matomo-admin"
        matomo_database_host: "FAKEHOST" # TO BE FIXED

    - name: K8S .:. Prepare Matomo Ingestion deployment file
      template:
        dest: "{{ wai_k8s_deployment_dir }}/{{ item }}/matomo-ingestion.yml"
        src: k8s/matomo-jail.yml.j2
      with_items: "{{ wai_k8s_namespaces }}" 

    - name: K8S .:. Deploy Matomo Ingestion
      kube:
        name: "{{ matomo_name }}"
        kubectl: "{{ wai_kubectl }}"
        filename: "{{ wai_k8s_deployment_dir }}/{{ item }}/matomo-ingestion.yml"
        state: "latest"
      with_items: "{{ wai_k8s_namespaces }}"

    # Matomo API
    - name: K8S .:. Prepare Matomo API template vars
      set_fact:
        matomo_app_filename: "/index.php"
        matomo_name: "matomo-api"
        matomo_pod_size_index: "matomo-api"
        matomo_nginx_jailed: true
        matomo_create_ingress: false
        matomo_enable_session: false
        matomo_database_user: "matomo-admin"
        matomo_database_host: "FAKEHOST" # TO BE FIXED

    - name: K8S .:. Prepare Matomo API deployment file
      template:
        dest: "{{ wai_k8s_deployment_dir }}/{{ item }}/matomo-api.yml"
        src: k8s/matomo-jail.yml.j2
      with_items: "{{ wai_k8s_namespaces }}" 

    - name: K8S .:. Deploy Matomo API
      kube:
        name: "{{ matomo_name }}"
        kubectl: "{{ wai_kubectl }}"
        filename: "{{ wai_k8s_deployment_dir }}/{{ item }}/matomo-api.yml"
        state: "latest"
      with_items: "{{ wai_k8s_namespaces }}"

    # Matomo Worker
    - name: K8S .:. Prepare Matomo Worker template
      set_fact:
        matomo_pod_size_index: "matomo-worker"
        matomo_database_user: "matomo-admin"
        matomo_database_host: "FAKEHOST" # TO BE FIXED

    - name: K8S .:. Prepare Matomo Worker deployment file
      template:
        dest: "{{ wai_k8s_deployment_dir }}/{{ item }}/matomo-worker.yml"
        src: k8s/matomo-worker.yml.j2
      with_items: "{{ wai_k8s_namespaces }}" 

    - name: K8S .:. Deploy Matomo Worker
      kube:
        name: "matomo-worker"
        kubectl: "{{ wai_kubectl }}"
        filename: "{{ wai_k8s_deployment_dir }}/{{ item }}/matomo-worker.yml"
        state: "latest"
      with_items: "{{ wai_k8s_namespaces }}" 

    # Deploy Redis secrets 
    - name: K8S .:. Prepare Redis Ingestion secrets
      template:
        dest: "{{ wai_k8s_deployment_dir }}/{{ item }}/redis-secrets.yml"
        src: k8s/redis-secrets.yml.j2
      with_items: "{{ wai_k8s_namespaces }}"

    - name: K8S .:. Deploy Redis Ingestion secrets
      kube:
        name: "redis-ingestion-secrets"
        kubectl: "{{ wai_kubectl }}"
        filename: "{{ wai_k8s_deployment_dir }}/{{ item }}/redis-secrets.yml"
        state: "latest"
      with_items: "{{ wai_k8s_namespaces }}"

    # Deploy Redis Sentinel
    - name: K8S .:. Prepare Redis & Sentinel template
      template:
        dest: "{{ wai_k8s_deployment_dir }}/{{ item }}/ingestion-redis.yml"
        src: k8s/redis-ingestion.yml.j2
      with_items: "{{ wai_k8s_namespaces }}" 

    - name: K8S .:. Deploy Redis & Sentinel
      kube:
        name: "redis-ingestion"
        kubectl: "{{ wai_kubectl }}"
        filename: "{{ wai_k8s_deployment_dir }}/{{ item }}/ingestion-redis.yml"
        state: "latest"
      with_items: "{{ wai_k8s_namespaces }}" 
