---
# Deploy K8S WAI Resources
- hosts: kube-master[0]
  tasks:
    - include_vars:
        file: password.yml

      # Install pyhton3
    - name: K8S Helm .:. Install python
      apt:
        update_cache: true
        name: 
          - python3
          - git
        state: present

    # Install PYHelm
    - name: K8S Helm .:. Install requirements
      pip:
        name: 
          - pygit2
          - pyhelm
          - grpcio

    # Install Prometheus
    - name: K8S Helm .:. Install Prometheus
      helm:
        namespace: monitoring
        name: prometheus
        chart: 
          name: prometheus
          source:
            type: git
            location: https://github.com/helm/charts.git
            path: stable/prometheus
        host: 10.233.5.45
        state: present
        values: 
          server:
            ingress:
              enabled: false
            persistentVolume:
              enabled: false
              storageClass: storage-nfs
          networkPolicy:
            enabled: false
          alertmanager:
            persistentVolume:
              enabled: false
              storageClass: storage-nfs

    # Install Grafana
    - name: K8S Helm .:. Install Grafana
      helm:
        namespace: monitoring
        name: grafana
        chart:
          name: grafana
          source:
            type: git
            location: https://github.com/helm/charts.git
            path: stable/grafana
        state: present
        host: 10.233.5.45
        values: 
          ingress:
            enabled: false
          persistence:
            enabled: false
            size: 8Gi
            storageClassName: storage-nfs
          initChownData:
            enabled: false
          resources:
            limits:
              cpu: "0.25"
              memory: "1024Mi"
            requests:    
              cpu: "0.25"
              memory: "512Mi"
