---
# Deploy K8S WAI Resources
- hosts: kube-master[0]
  tasks:
    - include_vars:
        file: password.yml

    # Base objects
    - name: K8S .:. Create destination directory
      file:
        path: "{{ wai_k8s_deployment_dir }}"
        state: directory

      # Install pyhton3
    - name: K8S Helm .:. Install python
      apt:
        update_cache: true
        name: 
          - python3
          - git
          - python3-pip
        state: present

    # Install PYHelm
    - name: K8S Helm .:. Install requirements
      pip:
        name: 
          - pygit2
          - pyhelm==2.11.5
          - grpcio

    # Get tiller clusterID
    - name: K8S Helm .:. Find tiller Cluster IP
      shell: kubectl get svc -n kube-system tiller-deploy -o=jsonpath='{.spec.clusterIP}'
      register: clusterIP

    # Install cert manager
    - name: K8S Helm .:. Download Cert-Manager requirements
      get_url:
        url: https://raw.githubusercontent.com/jetstack/cert-manager/release-0.11/deploy/manifests/00-crds.yaml
        dest: "{{ wai_k8s_deployment_dir }}/crds.yaml"

    - name: K8S Helm .:. Install Cert-Manager requirements
      raw: "{{ wai_kubectl }} apply --validate=false -f {{ wai_k8s_deployment_dir }}/crds.yaml"

    - name: K8S Helm .:. Install Cert-Manager
      helm:
        namespace: cert-manager
        name: cert-manager
        chart: 
          name: cert-manager
          version: "{{ helm.cert_manager.version }}"
          source:
            type: repo
            location: https://charts.jetstack.io
            path: jetstack/cert-manager
        host: "{{ clusterIP.stdout }}"
        state: present

    # Install Prometheus
    - name: K8S Helm .:. Install Prometheus
      helm:
        namespace: monitoring
        name: prometheus
        chart: 
          name: prometheus
          source:
            type: git
            location: https://github.com/helm/charts.git
            path: stable/prometheus
        host: "{{ clusterIP.stdout }}"
        state: present
        values: 
          server:
            ingress:
              enabled: false
            persistentVolume:
              enabled: true
              size: 50Gi
              storageClass: storage-heketi
          networkPolicy:
            enabled: false
          alertmanager:
            persistentVolume:
              enabled: true
              size: 2Gi
              storageClass: storage-heketi

    # Install Grafana
    - name: K8S Helm .:. Install Grafana
      helm:
        namespace: monitoring
        name: grafana
        chart:
          name: grafana
          source:
            type: git
            location: https://github.com/helm/charts.git
            path: stable/grafana
        state: present
        host: "{{ clusterIP.stdout }}"
        values: 
          ingress:
            enabled: false
          persistence:
            enabled: true
            size: 8Gi
            storageClassName: storage-heketi
          initChownData:
            enabled: false
          resources:
            limits:
              cpu: "0.25"
              memory: "1024Mi"
            requests:
              cpu: "0.25"
              memory: "512Mi"

    # Install Redis
    - name: K8S Helm .:. Install Redis
      helm:
        namespace: "{{ item[0] }}"
        name: "{{ item[1] }}-{{ item[0] }}"
        chart:
          name: redis
          source:
            type: git
            location: https://github.com/helm/charts.git
            path: stable/redis
        state: present
        host: "{{ clusterIP.stdout }}"
        values: 
          image:
            repository: "{{ wai_redis_image }}"
            tag: "{{ 'latest' if item[0] == 'wai-stag' else wai_redis_image_tag }}"
          cluster:
            enabled: true
            slaveCount: 2
          usePassword: true
          existingSecret: redis-master-secret
          existingSecretPasswordKey: "{{ item[1] }}-password"
          fullnameOverride: "{{ item[1] }}"
          metrics:
            enabled: true
            resources:
              limits:
                cpu: 100m
                memory: 128Mi
              requests:
                cpu: 100m
                memory: 128Mi
          master:
            extraFlags:
              - "--loadmodule /opt/bitnami/redis/bin/redisearch.so"
            persistence:
              enabled: true
              storageClass: storage-heketi
              size: 5Gi
            resources:
              limits:
                cpu: 250m
                memory: "{{ '4Gi' if item[1] == 'ingestion-redis' else '2Gi' }}"
              requests:
                cpu: 250m
                memory: "{{ '4Gi' if item[1] == 'ingestion-redis' else '1Gi' }}"
          slave:
            extraFlags:
              - "--loadmodule /opt/bitnami/redis/bin/redisearch.so"
            persistence:
              enabled: true
              storageClass: storage-heketi
              size: 5Gi
            resources:
              limits:
                cpu: 250m
                memory: "{{ '4Gi' if item[1] == 'ingestion-redis' else '2Gi' }}"
              requests:
                cpu: 250m
                memory: "{{ '4Gi' if item[1] == 'ingestion-redis' else '1Gi' }}"
          sentinel:
            usePassword: false
            enabled: true
            masterSet: "{{ item[1] }}-master"
            downAfterMilliseconds: 5000
            failoverTimeout: 5000
            resources:
              limits:
                cpu: 250m
                memory: 512Mi
              requests:
                cpu: 250m
                memory: 512Mi
      with_nested:
        - "{{ wai_k8s_namespaces }}" 
        - ["ingestion-redis", "application-redis"]

    # Install IPA Redis Search
    - name: K8S Helm .:. Install IPA Redisearch
      helm:
        namespace: "{{ item }}"
        name: "ipa-redisearch-{{ item }}"
        chart:
          name: redis
          source:
            type: git
            location: https://github.com/helm/charts.git
            path: stable/redis
        state: present
        host: "{{ clusterIP.stdout }}"
        values: 
          image:
            repository: "{{ wai_ipa_redisearch_image }}"
            tag: "{{ 'latest' if item[0] == 'wai-stag' else wai_ipa_redisearch_image_tag }}"
          cluster:
            enabled: true
            slaveCount: 2
          usePassword: true
          existingSecret: redis-master-secret
          existingSecretPasswordKey: ipa-redisearch-password
          fullnameOverride: ipa-redisearch
          metrics:
            enabled: true
            resources:
              limits:
                cpu: 100m
                memory: 128Mi
              requests:
                cpu: 100m
                memory: 128Mi
          master:
            persistence:
              enabled: true
              storageClass: storage-heketi
              size: 2Gi
            resources:
              limits:
                cpu: 250m
                memory: 2Gi
              requests:
                cpu: 250m
                memory: 1Gi
          slave:
            persistence:
              enabled: true
              storageClass: storage-heketi
              size: 2Gi
            resources:
              limits:
                cpu: 250m
                memory: 2Gi
              requests:
                cpu: 250m
                memory: 1Gi
          sentinel:
            usePassword: false
            enabled: true
            masterSet: "ipa-redisearch-master"
            downAfterMilliseconds: 5000
            failoverTimeout: 5000
            resources:
              limits:
                cpu: 250m
                memory: 512Mi
              requests:
                cpu: 250m
                memory: 512Mi
      with_items:
        - "{{ wai_k8s_namespaces }}" 

    # At the end.
    - name: K8S Helm .:. Prepare cluster issuer
      template:
        dest: "{{ wai_k8s_deployment_dir }}/99_cluster-issuer.yml"
        src: k8s/helm/cluster-issuer.yml.j2

    - name: K8S Helm .:. Deploy cluster issuer
      kube:
        name: "k8s-deployment"
        kubectl: "{{ wai_kubectl }}"
        state: "latest"
        filename: "{{ wai_k8s_deployment_dir }}/99_cluster-issuer.yml"
